version: '3.1'

services:
  db:
    image: "postgres"
    env_file:
      - config/database.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=200
    ports:
      - "5432:5432"
  client:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      POSTGRES_HOST: "db"
    env_file:
      - config/database.env
    depends_on:
      - db
    ports:
      - "7070:7070"
