version: '3.1'

services:
  db:
    image: "postgres"
    env_file:
      - config/database.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=200
  client:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./main --connection-string="host=db user=unicorn_user password=magical_password dbname=rainbow_database sslmode=disable"
    restart: always
    depends_on:
      - db
    ports:
      - "7070:7070"
